[[redirects]]
  from = "/blog/*"
  to = "/news/:splat"
  status = 200

[[redirects]]
  from = "/ar/*"
  to = "/ar/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404